spring.main:
  banner-mode: 'off'
  web-application-type: 'none'

logging.level:
  root: WARN
  org.springframework: INFO
  org.apache.kafka: WARN
  kafkablocks: INFO

spring.kafka:
  bootstrap-servers: kafka:9092
  consumer:
    auto-offset-reset: latest
    properties.spring.json.trusted.packages: "*"
  streams:
    application-id: examples-consumer-group
    cache-max-size-buffering: 0

kafkablocks:
  #processing.streams-thread-number: 2
  packageName: kafkablocks.examples.events
  eventTopic:
    PositionEvent: position
    DistanceEvent: distance
    SpeedEvent: speed
    AccelerationEvent: acceleration

  examples:
    springkafka:
      producer.interval: 200

