spring.main.banner-mode: 'off'

logging.level:
  root: WARN
  #org.springframework: WARN
  #org.apache.kafka: INFO
  ru.croc: INFO

spring.kafka:
  bootstrap-servers: kafka:9092
  streams:
    application-id: ReportProcessors
    cache-max-size-buffering: 0
  consumer:
    #auto-offset-reset: latest
    properties.spring.json.trusted.packages: "*"

whswd.kafka:
  processing.streams-thread-number: 8
  eventTopic:
    TrackableObjectMovementEvent: object-movement
    TrackableObjectCoordsEvent: object-coords
    ZoneEntranceEvent: zone-entrance
    TrackableObjectEntranceToZoneEvent: object-zone-entrance

spring.datasource:
  url: jdbc:postgresql://db:5432/whswd
  username: whswd
  password: whswd

spring.jpa:
  hibernate.ddl-auto: validate
  properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQL94Dialect
    temp.use_jdbc_metadata_defaults: false
