version: '2.4'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # image info: https://hub.docker.com/r/wurstmeister/kafka/
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # topics to create, in format: <topic name>:<partitions count>:<replicas count>
      KAFKA_CREATE_TOPICS: >-
        position:1:1,
        distance:1:1,
        speed:1:1,
        acceleration:1:1

  examples:
    image: examples
    container_name: examples
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      kafka:
        condition: service_started
